# Generated by Django 5.0.7 on 2024-07-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=255)),
                ('homekit', models.CharField(max_length=255)),
                ('awaykit', models.CharField(max_length=255)),
                ('specialkit', models.CharField(max_length=255)),
            ],
        ),
    ]
