# Generated by Django 5.0.7 on 2024-07-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='appleId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
